#!/usr/bin/env python

import os
import pickle
import argparse
import numpy as np

import sxp

cwd = os.path.abspath('.')
parser = argparse.ArgumentParser(description="Extract out-of-transit photometry"
    " from Spitzer data")
parser.add_argument('input', help='path to pickle file', type=str)
parser.add_argument('-t', '--times', help='times of 1st and 4th contact (comma-separated)',
    type=str, default=None)

args = parser.parse_args()

t1, t4 = [float(i) for i in args.times.split(',')]
mag, umag = sxp.phot.oot_phot(args.input, t1, t4)
