#!/usr/bin/env python

import os
import pickle
import argparse
import numpy as np

import sxp

cwd = os.path.abspath('.')
parser = argparse.ArgumentParser(description="Extract photometry"
    " from Spitzer data")
parser.add_argument('input', help='path to pickle file', type=str)
parser.add_argument('-r', '--radii', help='Aperture/annulus radii specification string',
    type=str, default='3_3_7')
parser.add_argument('-c', '--channel', help='IRAC channel', type=int, default=2)

args = parser.parse_args()


cornichon = pickle.load(open(args.input, 'rb'))

cen = cornichon['cen']
ims = cornichon['cube']

mag, umag = sxp.phot.spz_phot(ims, cen, args.radii, args.channel, verbose=True)
